// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxexlpoofgaevdwmfxvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZXhscG9vZmdhZXZkd21meHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTM5OTYsImV4cCI6MjA2OTA2OTk5Nn0.h5jzPCcwvNacyGpVeleeS5la-KZHm0Wjz9LcA7hAMgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});